import Foundation

enum GoogleUserProperty: String {
    case advancedPaid = "advance_paid"
    case coursesPaid = "courses_paid"
    case email = "email"
    case name = "name"
    case onBoardingExperience = "onboarding_experience"
    case onBoardingType = "onboarding_type"
    case phoneNumber = "phone"
    case signUpDate = "sign_up_date"
    case state = "state"
    case subscriptionCount = "subscription_count"
    case subscriptionExpiry = "subscription_expiry"
    case subscriptionPaid = "subscription_paid"
    case subscriptionStartDate = "subscription_start_date"
    case userActivated = "activated"
    case userUniqueId = "user_id"
    case utmCampaign = "utm_campaign"
    case utmContent = "utm_content"
    case utmMedium = "utm_medium"
    case utmSource = "utm_source"
    case utmTerm = "utm_term"
    case emailSettingOffer = "offers"
    case emailSettingsNewsLetter = "newsLetters"
    case fullName = "full_name"
    case firstName = "first_name"
    case lastName = "last_name"
}
