import Foundation

public enum PageName: String, CaseIterable {
    case getStarted = "GetStarted"
    case signIn = "Sign In"
    case signUp = "Sign Up"
    case signUpProfile = "Sign Up Profile"
    case privacyPolicy = "Privacy Policy"
    case termsConditions = "Terms Conditions"
    case resetPassword = "Reset Password"
    case forgetPassword = "Forget Password"
    case deleteAccount = "Delete Account"
    case changePassword = "Change Password"
    case verifyAccount = "Account Verified"
    case signOut = "Sign Out"
    case advancedCoursePlayList = "Advanced Course Playlist"
    case advancedCourseLandingPage = "Advanced Course Landing Page"
    case dashboard = "Dashboard"
    case playlist = "Playlist"
    case workshop = "Workshop"
    case upcomingWorkshop = "Upcoming Workshop"
    case recordedWorkshop = "Recorded Workshop"
    case workshopLandingPage = "Workshop Landing Page"
    case courseLandingPage = "Course Landing Page"
    case learningPath = "Learning Path"
    case allClasses = "All Classes"
    case allCourses = "All Courses"
    case moduleLandingPage = "Module Landing Page"
    case myProfile = "My Profile"
    case pricing = "Pricing"
    case paymentSuccessful = "Payment Successful"
    case courseVideoPage = "Course Video"
    case courseDiscussion = "Course Discussion"
    case courseAbout = "About Course"
    case courseLesson = "Course Lesson"
    case search = "Search"
    
    case contact = "Contact"
    case faq = "Faq"
    case language = "Language"
    case refund = "Refund"
    case settings = "Settings"
    case paymentHistory = "Payment History"
    case paymentDetails = "Payment Details"
    case emailSettings = "Email Settings"
    case downloads = "Downloads"
    
    case myLearning = "My Learning"
    case explore = "Explore"
}
